# Generated by Django 2.0.7 on 2018-07-29 15:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180726_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to=users.models.avatar_upload_handler),
        ),
    ]
